name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                ec2_instance: 
                    - ec2-3.88.214.68.compute-1.amazonaws.com
                    - ec2-35.172.226.171.compute-1.amazonaws.com

        steps:
            - name: 'Configurando SSH'
              run: |
                echo "${{ secrets.key1 }}" > key.pem
                chmod 400 key.pem

            - name: 'Actualizar repositorio en EC2'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.ec2_instance }} "
                cd /var/www/html && git pull"

            - name: 'Reiniciar Servicio'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.ec2_instance }} "sudo systemctl restart nginx"

            - name: 'Eliminar clave SSH'
              run: rm key.pem
